#!/bin/sh

# this is just a script which avoids having to install intltool just
# to translate one word!

# to add a translation - add the language to LINGUAS, copy
# favorites.pot to a po file for the language, and then run this script

for file in `cat LINGUAS`
do

if ! [ -d ../locale/$file/LC_MESSAGES ]; then
  mkdir -p ../locale/$file/LC_MESSAGES
fi

msgfmt $file.po
mv messages.mo ../locale/$file/LC_MESSAGES/favorites.mo

done
